// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCarePro.Data;

#nullable disable

namespace PetCarePro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629142659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PetCarePro.Classes.CareSchedule", b =>
                {
                    b.Property<int>("CareScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Feeding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CareScheduleId");

                    b.HasIndex("PetId");

                    b.ToTable("CareSchedules");
                });

            modelBuilder.Entity("PetCarePro.Classes.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Hoofdstraat 1",
                            Email = "jan@email.nl",
                            Name = "Jan Jansen",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "Dorpsstraat 5",
                            Email = "piet@email.nl",
                            Name = "Piet Pieters",
                            PhoneNumber = "0623456789"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "Stationsweg 10",
                            Email = "marie@email.nl",
                            Name = "Marie de Vries",
                            PhoneNumber = "0634567890"
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "Schoolstraat 15",
                            Email = "kees@email.nl",
                            Name = "Kees Bakker",
                            PhoneNumber = "0645678901"
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "Parklaan 8",
                            Email = "sophie@email.nl",
                            Name = "Sophie Jansen",
                            PhoneNumber = "0656789012"
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "Molenweg 22",
                            Email = "tom@email.nl",
                            Name = "Tom Visser",
                            PhoneNumber = "0667890123"
                        });
                });

            modelBuilder.Entity("PetCarePro.Classes.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PetId");

                    b.HasIndex("ClientId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Breed = "Labrador",
                            ChipNumber = "123456789",
                            ClientId = 1,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            MedicalHistory = "No medical issues",
                            Name = "Max",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 2,
                            Breed = "European Shorthair",
                            ChipNumber = "987654321",
                            ClientId = 2,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            MedicalHistory = "Allergic to certain food",
                            Name = "Luna",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 3,
                            Breed = "Golden Retriever",
                            ChipNumber = "456789123",
                            ClientId = 3,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            MedicalHistory = "Vaccinations up to date",
                            Name = "Bella",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 4,
                            Breed = "Maine Coon",
                            ChipNumber = "321654987",
                            ClientId = 4,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            MedicalHistory = "Needs daily medication",
                            Name = "Milo",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 5,
                            Breed = "German Shepherd",
                            ChipNumber = "654987321",
                            ClientId = 5,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            MedicalHistory = "No medical issues",
                            Name = "Rocky",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 6,
                            Breed = "British Shorthair",
                            ChipNumber = "789123456",
                            ClientId = 6,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            MedicalHistory = "Sensitive stomach",
                            Name = "Nala",
                            Species = "Cat"
                        });
                });

            modelBuilder.Entity("PetCarePro.Classes.Stay", b =>
                {
                    b.Property<int>("StayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("KennelNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StayId");

                    b.HasIndex("PetId");

                    b.ToTable("Stays");
                });

            modelBuilder.Entity("PetCarePro.Classes.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetCarePro.Classes.CareSchedule", b =>
                {
                    b.HasOne("PetCarePro.Classes.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCarePro.Classes.Pet", b =>
                {
                    b.HasOne("PetCarePro.Classes.Client", "Client")
                        .WithMany("Pets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PetCarePro.Classes.Stay", b =>
                {
                    b.HasOne("PetCarePro.Classes.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCarePro.Classes.Client", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
